In [2]:
#imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Gold_vs_Economic_Factors_2015_2026.csv")

## Data Inspection

In [4]:
df.head()

,Date,Gold_Price_XAU_USD,US_Dollar_Index_DXY,Crude_Oil_Price,Inflation_Rate_Pct
0,2015-01-01,1205.47,95.17,47.85,7.92
1,2015-01-02,1204.58,95.61,48.71,6.17
2,2015-01-03,1211.56,95.62,53.73,4.80
3,2015-01-04,1227.29,95.93,55.39,6.95
4,2015-01-05,1225.45,96.75,53.76,5.99

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4137 entries, 0 to 4136
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 4137 non-null   object
 1   Gold_Price_XAU_USD   4137 non-null   float64
 2   US_Dollar_Index_DXY  4137 non-null   float64
 3   Crude_Oil_Price      4137 non-null   float64
 4   Inflation_Rate_Pct   4137 non-null   float64
dtypes: float64(4), object(1)
memory usage: 161.7+ KB

In [6]:
df.describe()

,Gold_Price_XAU_USD,US_Dollar_Index_DXY,Crude_Oil_Price,Inflation_Rate_Pct
count,4137.000000,4137.000000,4137.000000,4137.000000
mean,2825.359197,55.311615,274.739901,5.065886
std,927.408308,17.148820,88.498329,2.011200
min,1106.380000,27.050000,47.850000,1.500000
25%,2034.880000,39.280000,227.140000,3.370000
50%,3047.790000,53.110000,282.700000,5.090000
75%,3625.970000,72.520000,320.750000,6.760000
max,4176.600000,97.090000,463.810000,8.500000